### ISSUE TITLE
Printing before entering an infinite loop results in no outputs

### ISSUE THREAD

**Issue by AlexCMueller** [ZweiSpeedruns/CraniumSmash#2]
Example program in order to reproduce this error:
`$48.[]`
Expected behavior: outputs "0", then hangs as opposed to leaving interpreter
Actual behavior: Hangs without leaving interpreter, without outputting "0"

Reason: Output is stored in a string local to the interpret() function, as opposed to printed as the dot, question mark, back-tick, colon, or semicolon are called.

Proposed to solution: allow output to be sent to a stream, as opposed to stored in a string buffered. This would allow streaming output to a string as is currently emulated, streaming to file, or streaming directly to cout, and allow shifting between these various streams without any hard-coded behavior inside of CraniumSmash.cpp or CraniumSmash.h.

**Comment by AlexCMueller** [comment]
Resolved by commit 25ac821

**Comment by ZweiSpeedruns** [comment]
help how do i close this

**Comment by ZweiSpeedruns** [comment]
close #2
